######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 31 13:45:34 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h threadcomsend.h
SOURCES += dialog.cpp main.cpp threadcomsend.cpp
QT+=network
