######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 28 14:58:29 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
