######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 13 08:44:01 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h threadcomsend.h
SOURCES += dialog.cpp main.cpp threadcomsend.cpp
QT+=network
